/* input : file contains info about allele counts (e.g., consensus_summary.txt from SHORE)                              */
/* output: <chr, <pos, count>> in global variable CHR2POS2ALLELE1_COUNT, CHR2POS2ALLELE2_COUNT, and CHR2POS2ERROR_COUNT */
/* date  : 2013-March-07                                                                                                */
/* file format:  chr_id  position consen_base coverage A_sup C_sup G_sup T_sup D_cup N_sup   other1....
                 chr1    1234567  A         	21      6      5    3     4      2    1      ignored...
                 chr2    4567123  C             21      6      5    3     4      2    1      ignored...
                 chr3    6712345  G             21      6      5    3     4      2    1      ignored...
                 chr4    3456712  T             21      6      5    3     4      2    1      ignored...
                 chr5    2345671  A             21      6      5    3     4      2    1      ignored...
   note: 1. only the fist 8 columns were recorded (in original script, we have added counts for '-' and 'N').
         2. this function requires global ALLELE1 nd ALLELE2 resulted from function read_marker.
*/

bool read_allele_counts(char* fconsensus);
